---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tomcat-app
  namespace: default
  labels:
    app: tomcat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-app
        image: ${REPOSITORY_TAG}
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-app
  namespace: default
spec:
  selector:
    app: tomcat-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8080
    port: 8080
